version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: text_to_sql_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: sales_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init_db:/docker-entrypoint-initdb.d
    networks:
      - text_to_sql_network

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: text_to_sql_api
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://admin:admin123@postgres:5432/sales_db
      - GROQ_API_KEY=${GROQ_API_KEY}
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    networks:
      - text_to_sql_network

volumes:
  postgres_data:

networks:
  text_to_sql_network:
    driver: bridge
